import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/port-icon.svg" />
        <title>Personal Portfolio</title>
      </head>
      <body className={inter.className}>
        <div className="bg-black">
        <Navbar />
        {children}
        <Footer />
        </div>
      </body>
    </html>
  );
}
